# -*- coding: utf-8 -*-
"""SuwardaDDP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rdjNNe1nkG8DBkJs2pLqD58jqv4m8yAN
"""

kendaraan =["ngengggg","motor","honda",150]
print("nama kendaraan :",kendaraan[0])
print("jenis kendaraan :",kendaraan[1])
print("merk kendaraan :",kendaraan[2])
print("cc kendaraan :",kendaraan[3])

kendaraan.append("hitam")
print(kendaraan)
kendaraan.append("2")
print(kendaraan)
kendaraan.append(75000000)
print(kendaraan)

kendaraan.pop(1)
print(kendaraan)

pilihan  = int(input("""Silahkan pilih nomor dibawah ini
untuk menggunakan tools dibawah ini
==================================
Pilihan
==================================
1. Pertambahan
2. Pengurangan
3. Pembagian
=================================
Pilihan mu? """))
match pilihan:
    case 1:
        print("menghitung luas persegi")
        sisi = int(input("masukan sisi?"))
        luasP = int(sisi*sisi)
        print("luas persegi adalah", luasP)
    case 2:
        print(" menghitung luas lingkaran ")
        jari = float(input("masukan jari-jari "))
        luasL = float(3.14*jari*jari)
        print("luas lingkaran adalah", luasL)
    case 3:
        print ("Menghitung luas segitiga ")
        alas =int(input("masukan alas"))
        tinggi =int(input("masukan tinggi "))
        luas =int(alas*tinggi/2)
        print ("luas segitiga adalah", luasS)